# HotStream 配置文件

framework:
  name: "HotStream"
  version: "0.1.0"
  debug: false
  log_level: "INFO"

plugins:
  auto_discover: true
  plugin_dirs: []

scheduler:
  enabled: true
  check_interval: 10
  max_concurrent_tasks: 10

storage:
  default_type: "json"
  output_dir: "output"
  compression: false

crawler:
  user_agent: "HotStream/0.1.0 (Data Collector)"
  timeout: 30
  retry_count: 3
  delay_range: [1, 3]
  concurrent_requests: 5

platforms:
  twitter:
    enabled: true
    rate_limit:
      requests_per_minute: 100
      requests_per_hour: 1000
    config:
      headless: true
      viewport: { width: 1920, height: 1080 }
  
  medium:
    enabled: true
    rate_limit:
      requests_per_minute: 60
      requests_per_hour: 500
    config:
      headless: true
  
  zhihu:
    enabled: true
    rate_limit:
      requests_per_minute: 50
      requests_per_hour: 300
    config:
      headless: true
  
  juejin:
    enabled: true
    rate_limit:
      requests_per_minute: 40
      requests_per_hour: 200
    config:
      headless: true

security:
  encrypt_credentials: true
  proxy_rotation: true
  user_agent_rotation: true
  respect_robots_txt: true

monitoring:
  enabled: true
  metrics_interval: 300
  log_file: "logs/hotstream.log"
  log_rotation: "1 day"
  log_retention: "30 days"